### ISSUE TITLE
bug: Unable to compile on iOS with version 0.10.1 (its working with 0.9.3)

### ISSUE THREAD

**Issue by itryp** [arthurfiorette/axios-cache-interceptor#179]
### Describe the bug

By running axios and axios-cache-interceptor on iOS device using expo project, the compilation failed with the following error:

```
iOS Bundling failed 5590ms
While trying to resolve module `axios-cache-interceptor` from file `[...]/Api.tsx`, the package `[...]/node_modules/axios-cache-interceptor/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`[...]/node_modules/axios-cache-interceptor/dist/index.cjs`. Indeed, none of these files exist:

  * [...]/node_modules/axios-cache-interceptor/dist/index.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * [...]/node_modules/axios-cache-interceptor/dist/index.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
```
If I rollback to an older version of the axios-cache-intereceptor (like 0.9.3), the compilation is working as expected.

### To Reproduce

1) Create new expo project (dont know if the issue is present on bare projects)

2) Install mandatory dependencies 

```yarn add axios axios-cache-interceptor ```

```
{
    "axios": "^0.26.1",
    "axios-cache-interceptor": "^0.10.1",
}
```

3) expo start or yarn start
4) Launch the packager on a real iOS device (probably the issue is present on emulator too)

## Expected behavior

The build should succeed

### Additional context

- Axios: `0.26.1`
- Axios Cache Interceptor: `0.10.1`
- Environment : expo app

**Comment by arthurfiorette** [comment]
I guess that using .cjs to denotate the file as commonjs is breaking the compilation.

All your build / environment deps are up to date?

The extensions .cjs and .mjs should be standard already.

**Comment by arthurfiorette** [comment]
Have you tried  https://stackoverflow.com/a/70472986?

**Comment by itryp** [comment]
Thank you for your fast answer @arthurfiorette. Indeed, with the suggested fix from stackoverflow it's working with the last version. Your help was much appreciated, I wasn't able to understand fully the issue by myself.

**Comment by arthurfiorette** [comment]
Happy to help!

It was reading the index.cjs as a part of the filename, like index.test or index.controller and etc.
